version: 0.2

env:
  variables:
    CODEBUILD_CONFIG_SANDBOX_JUPYTER_SERVER: "true"

phases:
  install:
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
      # - echo "Waiting 60 seconds for Jupyter setup..."
      # - sleep 60
      - echo "Starting build phase..."
      - java -version

  build:
    commands:
      - echo "Compiling Java program..."
      - javac SimpleDemo.java

  post_build:
    commands:
      - echo "Running the program..."
      - java SimpleDemo

artifacts:
  files:
    - SimpleDemo.class
    - SimpleDemo.java
